paths: 
  /api/products/:
    get:
      summary: Obtiene todos los productos con paginación
      tags: 
        - Products
      parameters:
        - name: limit
          in: query
          required: false
          description: Número máximo de productos por página (por defecto 5)
          schema:
            type: integer
            example: 5
        - name: numPage
          in: query
          required: false
          description: Número de la página a solicitar (por defecto 1)
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: Los productos fueron obtenidos correctamente de la base de datos
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de la conexión con la base de datos.
  /api/products:
    post:
      summary: Crea un nuevo producto
      tags: 
        - Products
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#components/requestBodies/createProduct'
      responses: 
        "201":
          description: El producto fue creado exitosamente
  
  /api/products/{pid}:
    get: 
      summary: Obtiene un producto a partir de su id
      tags: 
        - Products
      parameters: 
        - name: pid
          in: path
          required: true
          description: id del producto que se desea solicitar
          schema:
            type: string
      responses:
        "200":
          description: Producto encontrado correctamente
          content: 
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor
  
    put:
      summary: Actualiza un producto por su id
      tags:
        - Products
      parameters: 
        - name: pid
          in: path
          required: true
          description: id del producto que se desea actualizar
          schema:
            type: string
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'
      responses: 
        "200":
          description: El producto fue actualizado exitosamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor

    delete:
      summary: Elimina un producto por su id
      tags: 
        - Products
      parameters: 
        - name: pid
          in: path
          required: true
          description: id del producto que se desea eliminar
          schema:
            type: string
      responses: 
        "200":
          description: El producto fue eliminado exitosamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor

components:
  schemas:  
    Product:
      type: object
      properties:
        _id:
          type: string
          description: Id autogenerado de Mongo
        name:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        stock:
          type: integer
          description: Cantidad disponible del producto
      example:
        _id: ObjectId('alksfdasdflajasjdflasdfas')
        name: Producto 1
        description: Descripción del producto 1
        price: 100.0
        stock: 50
  
  requestBodies:
    createProduct:
      type: object
      properties:
        name:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        stock:
          type: integer
          description: Cantidad disponible del producto
      example:
        name: Producto 2
        description: Este es el producto 2
        price: 200.0
        stock: 30
    
    updateProduct:
      type: object
      properties:
        name:
          type: string
          description: Nombre del producto (opcional)
        description:
          type: string
          description: Descripción del producto (opcional)
        price:
          type: number
          description: Precio del producto (opcional)
        stock:
          type: integer
          description: Cantidad disponible del producto (opcional)
      example:
        name: Producto 2 actualizado
        description: Este es el producto 2 con descripción actualizada
        price: 220.0
        stock: 25